export const POPUP_BUILDER = "POPUP_BUILDER"
export const PIZZA_COUNTER_ADD = "PIZZA_COUNTER_ADD"
export const PIZZA_COUNTER_REMOVE = "PIZZA_COUNTER_REMOVE"
export const PIZZA_COUNTER_SET = "PIZZA_COUNTER_SET"
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const COUNT_SINGLE_PRICE = 'COUNT_SINGLE_PRICE'